import 'package:flutter/cupertino.dart';

import 'product.dart';

class ProductsRepository {
  static List<Product> loadProducts(Category category) {
    const allProducts = <Product>[
      Product(
        category: Category.labios,
        //id: 0,
        image: Image(image: AssetImage('images/0-0.jpg')),
        isFeatured: true,
        name: 'KIT LABIAL MATE',
        price: 700,
      ),
      Product(
        category: Category.labios,
        image: Image(image: AssetImage('images/1-0.jpg')),
        //id: 1,
        isFeatured: true,
        name: 'TINTALINE LABIOS',
        price: 55,
      ),
      Product(
        category: Category.labios,
        image: Image(image: AssetImage('images/2-0.jpg')),
        //id: 2,
        isFeatured: false,
        name: 'KIT LABIAL HUMECTANTE',
        price: 35,
      ),
      Product(
        category: Category.labios,
        image: Image(image: AssetImage('images/3-0.jpg')),
        //id: 3,
        isFeatured: true,
        name: 'TINTA MATE',
        price: 74,
      ),
      Product(
        category: Category.labios,
        image: Image(image: AssetImage('images/4-0.jpg')),
        //id: 4,
        isFeatured: false,
        name: 'LABIAL MATE',
        price: 36,
      ),
      Product(
        category: Category.labios,
        image: Image(image: AssetImage('images/5-0.jpg')),
        //id: 5,
        isFeatured: false,
        name: 'LABIAL HUMECTANTE',
        price: 30,
      ),
      Product(
        category: Category.labios,
        image: Image(image: AssetImage('images/6-0.jpg')),
        //id: 6,
        isFeatured: false,
        name: 'DELINEADOR RETRÁCTIL',
        price: 32,
      ),
      Product(
        category: Category.labios,
        image: Image(image: AssetImage('images/7-0.jpg')),
        //id: 7,
        isFeatured: true,
        name: 'BRILLO LABIAL',
        price: 32,
      ),
      Product(
        category: Category.ojos,
        image: Image(image: AssetImage('images/8-0.jpg')),
        //id: 8,
        isFeatured: true,
        name: 'TINTALINE OJOS',
        price: 55,
      ),
      Product(
        category: Category.ojos,
        image: Image(image: AssetImage('images/9-0.jpg')),
        //id: 9,
        isFeatured: true,
        name: 'SOMBRA PARA CEJAS',
        price: 34,
      ),
      Product(
        category: Category.ojos,
        image: Image(image: AssetImage('images/10-0.jpg')),
        //id: 10,
        isFeatured: false,
        name: 'SOMBRA EN POLVO',
        price: 18,
      ),
      Product(
        category: Category.ojos,
        image: Image(image: AssetImage('images/11-0.jpg')),
        //id: 11,
        isFeatured: false,
        name: 'PLUMÍN PARA CEJAS',
        price: 64,
      ),
      Product(
        category: Category.ojos,
        image: Image(image: AssetImage('images/12-0.jpg')),
        //id: 12,
        isFeatured: false,
        name: 'SOMBRA INDIVIDUAL',
        price: 38,
      ),
      Product(
        category: Category.ojos,
        image: Image(image: AssetImage('images/13-0.jpg')),
        //id: 13,
        isFeatured: true,
        name: 'SOMBRA CUARTETO',
        price: 41,
      ),
      Product(
        category: Category.ojos,
        image: Image(image: AssetImage('images/14-0.jpg')),
        //id: 14,
        isFeatured: true,
        name: 'PRIMER PARA OJOS',
        price: 38,
      ),
      Product(
        category: Category.ojos,
        image: Image(image: AssetImage('images/15-0.jpg')),
        //d: 15,
        isFeatured: true,
        name: 'MASCARA PESTAÑAS',
        price: 65,
      ),
      Product(
        category: Category.rostro,
        image: Image(image: AssetImage('images/16-0.jpg')),
        //d: 16,
        isFeatured: true,
        name: 'PRIMER PARA ROSTRO',
        price: 130,
      ),
      Product(
        category: Category.rostro,
        image: Image(image: AssetImage('images/17-0.jpg')),
        //id: 17,
        isFeatured: false,
        name: 'RUBOR',
        price: 40,
      ),
      Product(
        category: Category.rostro,
        image: Image(image: AssetImage('images/18-0.jpg')),
        //id: 18,
        isFeatured: true,
        name: 'POLVO TRASLUCIDO',
        price: 74,
      ),
      Product(
        category: Category.rostro,
        image: Image(image: AssetImage('images/19-0.jpg')),
        //id: 19,
        isFeatured: false,
        name: 'MAQUILLAJE LIQUIDO',
        price: 112,
      ),
      Product(
        category: Category.rostro,
        image: Image(image: AssetImage('images/20-0.jpg')),
        //id: 20,
        isFeatured: false,
        name: 'MAQUILLAJE COMPACTO',
        price: 79,
      ),
      Product(
        category: Category.rostro,
        image: Image(image: AssetImage('images/21-0.jpg')),
        //id: 21,
        isFeatured: false,
        name: 'GLITTER',
        price: 18,
      ),
      Product(
        category: Category.rostro,
        image: Image(image: AssetImage('images/22-0.jpg')),
        //id: 22,
        isFeatured: false,
        name: 'CORRECTOR',
        price: 23,
      ),
      Product(
        category: Category.rostro,
        image: Image(image: AssetImage('images/23-0.jpg')),
        //id: 23,
        isFeatured: false,
        name: 'POLVO FIJADOR',
        price: 74,
      ),
      Product(
        category: Category.rostro,
        image: Image(image: AssetImage('images/24-0.jpg')),
        //id: 24,
        isFeatured: true,
        name: 'KIT MAQUILLAJE',
        price: 136,
      ),
      Product(
        category: Category.rostro,
        image: Image(image: AssetImage('images/25-0.jpg')),
        //id: 25,
        isFeatured: false,
        name: 'ILUMINADOR',
        price: 44,
      ),
      Product(
        category: Category.rostro,
        image: Image(image: AssetImage('images/26-0.jpg')),
        //id: 26,
        isFeatured: false,
        name: 'CONTORNEADOR',
        price: 92,
      ),
      Product(
        category: Category.rostro,
        image: Image(image: AssetImage('images/27-0.jpg')),
        //id: 27,
        isFeatured: true,
        name: 'BRONCEADOR',
        price: 40,
      ),
      Product(
        category: Category.manos,
        image: Image(image: AssetImage('images/28-0.jpg')),
        //id: 28,
        isFeatured: true,
        name: 'SUEÑO DE NOVIA',
        price: 14,
      ),
      Product(
        category: Category.manos,
        image: Image(image: AssetImage('images/29-0.jpg')),
        //id: 29,
        isFeatured: true,
        name: 'SIRENA',
        price: 14,
      ),
      Product(
        category: Category.manos,
        image: Image(image: AssetImage('images/30-0.jpg')),
        //id: 30,
        isFeatured: true,
        name: 'PASTEL',
        price: 14,
      ),
      Product(
        category: Category.manos,
        image: Image(image: AssetImage('images/31-0.jpg')),
        //id: 31,
        isFeatured: false,
        name: 'PASION NOCTURNA',
        price: 14,
      ),
      Product(
        category: Category.manos,
        image: Image(image: AssetImage('images/32-0.jpg')),
        //id: 32,
        isFeatured: false,
        name: 'NEON',
        price: 14,
      ),
      Product(
        category: Category.manos,
        image: Image(image: AssetImage('images/33-0.jpg')),
        //id: 33,
        isFeatured: true,
        name: 'METAL MATE',
        price: 14,
      ),
      Product(
        category: Category.manos,
        image: Image(image: AssetImage('images/34-0.jpg')),
        //id: 34,
        isFeatured: false,
        name: 'FRUTAS',
        price: 14,
      ),
      Product(
        category: Category.brochas,
        image: Image(image: AssetImage('images/brocha1.jpg')),
        //id: 34,
        isFeatured: false,
        name: 'BROCHA PROFESIONAL No. 1',
        price: 164,
      ),
      Product(
        category: Category.brochas,
        image: Image(image: AssetImage('images/brocha2.jpg')),
        //id: 34,
        isFeatured: false,
        name: 'BROCHA PROFESIONAL No. 2',
        price: 121,
      ),
      Product(
        category: Category.brochas,
        image: Image(image: AssetImage('images/brocha3.jpg')),
        //id: 34,
        isFeatured: false,
        name: 'BROCHA PROFESIONAL No. 3',
        price: 74,
      ),
      Product(
        category: Category.brochas,
        image: Image(image: AssetImage('images/brocha4.jpg')),
        //id: 34,
        isFeatured: false,
        name: 'BROCHA PROFESIONAL No. 4',
        price: 125,
      ),
      Product(
        category: Category.brochas,
        image: Image(image: AssetImage('images/brocha5.jpg')),
        //id: 34,
        isFeatured: false,
        name: 'BROCHA PROFESIONAL No. 5',
        price: 391,
      ),
      Product(
        category: Category.brochas,
        image: Image(image: AssetImage('images/brocha6.jpg')),
        //id: 34,
        isFeatured: false,
        name: 'BROCHA PROFESIONAL No. 6',
        price: 189,
      ),
      Product(
        category: Category.brochas,
        image: Image(image: AssetImage('images/brocha7.jpg')),
        //id: 34,
        isFeatured: false,
        name: 'BROCHA PROFESIONAL No. 7',
        price: 140,
      ),
      Product(
        category: Category.brochas,
        image: Image(image: AssetImage('images/brocha8.jpg')),
        //id: 34,
        isFeatured: false,
        name: 'BROCHA PROFESIONAL No. 8',
        price: 209,
      ),
      Product(
        category: Category.brochas,
        image: Image(image: AssetImage('images/brocha9.jpg')),
        //id: 34,
        isFeatured: false,
        name: 'BROCHA PROFESIONAL No. 9',
        price: 163,
      ),
      Product(
        category: Category.brochas,
        image: Image(image: AssetImage('images/brocha11.jpg')),
        //id: 34,
        isFeatured: false,
        name: 'BROCHA PROFESIONAL No. 11',
        price: 64,
      ),
      Product(
        category: Category.brochas,
        image: Image(image: AssetImage('images/brocha12.jpg')),
        //id: 34,
        isFeatured: false,
        name: 'BROCHA PROFESIONAL No. 12',
        price: 62,
      ),
      Product(
        category: Category.brochas,
        image: Image(image: AssetImage('images/brocha13.jpg')),
        //id: 34,
        isFeatured: false,
        name: 'BROCHAS PROFESIONAL No. 13',
        price: 64,
      ),
      Product(
        category: Category.brochas,
        image: Image(image: AssetImage('images/brocha15.jpg')),
        //id: 34,
        isFeatured: false,
        name: 'BROCHA PROFESIONAL No. 15',
        price: 67,
      ),
      Product(
        category: Category.brochas,
        image: Image(image: AssetImage('images/brocha16.jpg')),
        //id: 34,
        isFeatured: false,
        name: 'BROCHA PROFESIONAL No. 16',
        price: 65,
      ),
      Product(
        category: Category.brochas,
        image: Image(image: AssetImage('images/brocha19.jpg')),
        //id: 34,
        isFeatured: false,
        name: 'BROCHA PROFESIONAL No. 19',
        price: 57,
      ),
      Product(
        category: Category.brochas,
        image: Image(image: AssetImage('images/brocha20.jpg')),
        //id: 34,
        isFeatured: false,
        name: 'BROCHA PROFESIONAL No. 20',
        price: 59,
      ),
      Product(
        category: Category.brochas,
        image: Image(image: AssetImage('images/brocha21.jpg')),
        //id: 34,
        isFeatured: false,
        name: 'BROCHA PROFESIONAL No. 21',
        price: 64,
      ),
      Product(
        category: Category.brochas,
        image: Image(image: AssetImage('images/brocha22.jpg')),
        //id: 34,
        isFeatured: false,
        name: 'BROCHA PROFESIONAL No. 22',
        price: 62,
      ),
      Product(
        category: Category.brochas,
        image: Image(image: AssetImage('images/brocha23.jpg')),
        //id: 34,
        isFeatured: false,
        name: 'BROCHA PROFESIONAL No. 23',
        price: 57,
      ),
      Product(
        category: Category.brochas,
        image: Image(image: AssetImage('images/brocha24.jpg')),
        //id: 34,
        isFeatured: false,
        name: 'BROCHA PROFESIONAL No. 24',
        price: 56,
      ),
      Product(
        category: Category.brochas,
        image: Image(image: AssetImage('images/brocha25.jpg')),
        //id: 34,
        isFeatured: false,
        name: 'BROCHA PROFESIONAL No. 25',
        price: 79,
      ),
      Product(
        category: Category.brochas,
        image: Image(image: AssetImage('images/brocha26.jpg')),
        //id: 34,
        isFeatured: false,
        name: 'BROCHA PROFESIONAL No. 26',
        price: 61,
      ),
      Product(
        category: Category.brochas,
        image: Image(image: AssetImage('images/brocha27.jpg')),
        //id: 34,
        isFeatured: false,
        name: 'BROCHA PROFESIONAL No. 27',
        price: 88,
      ),
      Product(
        category: Category.brochas,
        image: Image(image: AssetImage('images/fundabrochas.jpg')),
        //id: 34,
        isFeatured: false,
        name: 'FUNDA PARA SET DE BROCHAS',
        price: 387,
      ),
      Product(
        category: Category.esponjas,
        image: Image(image: AssetImage('images/esponja.jpg')),
        //id: 34,
        isFeatured: false,
        name: 'ESPONJAS',
        price: 38,
      ),
      Product(
        category: Category.esponjas,
        image: Image(image: AssetImage('images/esponjasColores.jpg')),
        //id: 34,
        isFeatured: false,
        name: 'ESPONJAS PIQUITOS DE COLORES',
        price: 108,
      ),
      Product(
        category: Category.cosmetiquera,
        image: Image(image: AssetImage('images/cosmetiquera1.jpg')),
        //id: 34,
        isFeatured: false,
        name: 'COSMETIQUERA DISEÑO FLORECER',
        price: 60,
      ),
      Product(
        category: Category.cosmetiquera,
        image: Image(image: AssetImage('images/cosmetiquera2.jpg')),
        //id: 34,
        isFeatured: false,
        name: 'COSMETIQUERA DISEÑO RESPLANDECER',
        price: 60,
      ),
      Product(
        category: Category.cosmetiquera,
        image: Image(image: AssetImage('images/cosmetiquera3.jpg')),
        //id: 34,
        isFeatured: false,
        name: 'COSMETIQUERA DISEÑO RENACER',
        price: 60,
      )
    ];
    if (category == Category.todos) {
      return allProducts;
    } else {
      return allProducts.where((Product p) {
        return p.category == category;
      }).toList();
    }
  }
}
